---
- name: Login As Super User
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"

- name: Change project to {{ namespace }}
  command: "oc project {{ namespace }}"

- include: "generatevm.yml"

- name: Delete Vitual Machine
  command: oc delete -f /tmp/vm.yaml
