---
- name: Login as "{{ admin_user }}" user
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"

- name: Change project to {{ namespace }}
  command: "oc project {{ namespace }}"

- include: "generatevm.yml"

- name: Create Virtual Machine
  command: "oc apply -f /tmp/vm.yaml"
